### ISSUE TITLE
Trying to list just hangs with no error

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/packagedb-cli#28]
I tried running this:
```
$ pkgdb-cli --user ralph list
```

And it just hung there with no error.

**Comment by pypingou** [comment]
Well there are two things there:

``pkgdb-cli --user ralph list`` identifies you as user ``ralph`` and then list, thus list all the packages in pkgdb:
````
$ time pkgdb-cli  --user ralph list
....
Total: 19387 packages
pkgdb-cli --user ralph list  1.96s user 0.51s system 1% cpu 3:25.48 total
````

While:
``pkgdb-cli list --user ralph`` will lists all the packages maintained by the user ``ralph`` and that is sensibly faster:
````
$ time pkgdb-cli list --user ralph
....
Total: 260 packages
pkgdb-cli list --user ralph  0.37s user 0.06s system 13% cpu 3.210 total
````

**Comment by ralphbean** [comment]
Wow.  Thanks :)

Perhaps those two examples could be added to the ``--help`` message for new users?  I didn't expect that order would matter so much.  ;)
