### ISSUE TITLE
Show which tests were performed in pkgdb-admin

### ISSUE THREAD

**Issue by tyll** [fedora-infra/packagedb-cli#53]
IMHO it would be nicer if pkgdb-admin would list which checks were performed to be able to decide whether nothing was missed. I would suggest some output like:

```
GOOD: $username is in packager group
GOOD: $package is not in RHEL
BAD: Review bug $bugurl is approved by a packager
```

What do you think?

**Comment by pypingou** [comment]
Works for me, maybe with a
``
[+]
[-] 
``
 approach and we could add some color as we already have the logic for it on pkgdb-cli

**Comment by tyll** [comment]
sounds good

**Comment by pypingou** [comment]
Fixed in https://github.com/fedora-infra/packagedb-cli/pull/55
