### ISSUE TITLE
pkgdb-admin should check that a review was not approved by the packager requesting a new package

### ISSUE THREAD

**Issue by tyll** [fedora-infra/packagedb-cli#56]
It is not allowed to review ones own package

**Comment by pypingou** [comment]
I think that's already there, isn't it?

**Comment by tyll** [comment]
currently it only checks that the package was approved by a packager afaics. But it can be added easily once #55 was merged, since both would touch the same code. However, I am also wondering whether it makes sense to check this better in pkdbd directly - also some other checks could be enforced direclty in pkdbdb and maybe are already, so they do not need to be checked twice.

**Comment by pypingou** [comment]
You mean this? https://github.com/fedora-infra/pkgdb2/pull/281

But this is only valid if the user provides the ticket number and click on the `populates` button

**Comment by tyll** [comment]
AFAICS there is no check about who set the review flag to "+". If the checks in that code are only performed optionally, then they should be made mandatory btw. see for example https://bugzilla.redhat.com/show_bug.cgi?id=1280422 which was accidently approved without being properly reviewed.

**Comment by pypingou** [comment]
I disagree about having pkgdb making these checks, I believe this is the work of pkgdb-admin and I still want to make pkgdb somewhat agnostic so that other organizations can also use it.
