### ISSUE TITLE
Perform checks for admin actions in pkgdb before accepting them

### ISSUE THREAD

**Issue by tyll** [fedora-infra/packagedb-cli#62]
IMHO pkgdb should already perform the sanity checks that are later done in pkgdb-admin.

Some of them are already implemented in pkgdb:
- [Check for RHEL pkgs](https://github.com/fedora-infra/pkgdb2/blob/master/pkgdb2/lib/__init__.py#L100)
- [Check validity of review requests](https://github.com/fedora-infra/pkgdb2/blob/master/pkgdb2/api/extras.py#L699)

However there are more in pkgdb-admin and the review requests are not enforced in pkgdb. To give requesters a faster response and to decrease errors by admins, the checks should already be performed in pkgdb and requests should not be accepted, if they violate required checks. Since the checks are Fedora specific, an configuration option might be a good idea to disable certain checks. However there is already a lot of Fedora/EPEL specific code in pkgdb, so unless there is some actually wanting to use pkgdb2 for a non-Fedora related project, it might not be worth the trouble.

Adding the checks to pkgdb would also allow to automate more requests eventually.

This was previously discussed in #56 but since the issue is about a different problem, it makes more sense to discuss it in a separate issue.

**Comment by pypingou** [comment]
There was a clear signal from rel-eng that they do not want more automation on branch/git creation, so I don't think expending the logic on the pkgdb side brings us much.

**Comment by tyll** [comment]
Even without fully automation, there is still the advantage of immediate feedback for users if there is something wrong with a request. Also if it is half-automated with all checks already done by pkdb, the pkgdb-admin runs would be a lot faster. Currently pkgdb-admin takes a while for all the checks before one can approve the request. If all requests were already checked, pkgdb-admin could just show an overview of all requests and make it possible to approve them all at once.

**Comment by pypingou** [comment]
but a CLI tool can be slower than a web-app, so while I agree some of the tests could be ported to pkgdb, I don't think we want all of them as otherwise the risk to time-out increases quite a bit

**Comment by pypingou** [comment]
I've added some of the checks we're performing in pkgdb-admin to pkgdb itself, when the user asks for info to be synced from bugzilla, but checks such as checking if the person who approved the review is in the packager group is not something I want to do in pkgdb, for the reason mentioned above.
