### ISSUE TITLE
"pkgdb-cli request" fails with "OpenID transaction in progress"

### ISSUE THREAD

**Issue by contyk** [fedora-infra/packagedb-cli#94]
I was trying to remove myself from a number of packages and ran into this issue. Every pkgdb-cli request fails with the following error:

$ pkgdb-cli --user psabata request --cancel fvsp all all
ServerError(https://admin.fedoraproject.org/pkgdb/api/package/acl/, 200, Error returned from json module while processing https://admin.fedoraproject.org/pkgdb/api/package/acl/: Expecting value: line 2 column 1 (char 1)

<html>
<head>
  <title>OpenID transaction in progress</title>
</head>
(...)

I'm using packagedb-cli-2.12-1.fc23.noarch.

**Comment by pypingou** [comment]
This looks similar to https://bugzilla.redhat.com/1317579 no?

**Comment by contyk** [comment]
It appears to be.

**Comment by contyk** [comment]
The workaround described in the bug report works for me too.

**Comment by puiterwijk** [comment]
And we have a fix: fedora-infra/python-fedora#182

**Comment by puiterwijk** [comment]
This has been fixed in python-fedora 0.8.0, which is now in F22, F23, F24 and rawhide testing.
